### ISSUE TITLE
Increase in `exit code 1` failures during builds

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#185]
I don’t know whether this is a host issue (I use GitHub Actions to publish to Cloudflare Pages) or something that’s changed in Pagefind 0.10.6, but I note it here just in case it’s the latter...

Since 0.10.6 came out, I’ve seen a marked increase in `exit code 1` failures in the build process. I use two different repos, one for Hugo and one for Eleventy, to build my site as I choose at the time, and have seen this in both. In each case, the GitHub Action has a backup that restarts a failed build, and it seems the backup typically does better with the Pagefind part.

Examples (in each case, the failure followed by the success):
- Eleventy repo: https://github.com/brycewray/eleventy_site/actions/runs/3760996487/jobs/6392278556 and https://github.com/brycewray/eleventy_site/actions/runs/3761003689/jobs/6392292239
- Hugo repo: https://github.com/brycewray/hugo_site/actions/runs/3740944817 and https://github.com/brycewray/hugo_site/actions/runs/3740950420/jobs/6349929489

Please advise if I can provide more information. And please don’t waste any holidays-related time on this — it’ll wait. 🎄 👪 🥳

**Comment by bglw** [comment]
Hmm there are a few things it could be — most likely the binary failing to download for some reason. 

`npx` is annoying and suppresses the logging I _(think I)_ have in place for some of these situations, so a good first step would be to add `pagefind` to your `package.json`, alongside an npm script like `"pagefind": "pagefind --source _site"`. Then in your action, run `npm run pagefind`.

This probably won't fix the error, but the npm install will log better errors than the npx command will, which will help us dig into it further 🙂

**Comment by bglw** [comment]
I have had weird intermittent npx issues on GitHub actions myself, so I tend to download the binaries directly. If you want to fix it over the holiday break this would be something to look into. 

Example (for one of our other projects with the same release setup):
https://github.com/CloudCannon/pagefind/blob/f133aa06303c4198c916a080d3d40b3267fce581/.github/workflows/test.yml#L77-L82

Untested, but writing off the cuff:
```yml
      - name: Install pagefind
        uses: supplypike/setup-bin@v1
        with:
          uri: "https://github.com/CloudCannon/pagefind/releases/download/v${{env.PAGEFIND_VERSION}}/humane-v${{env.PAGEFIND_VERSION}}-x86_64-unknown-linux-musl.tar.gz"
          name: "pagefind"
          version: ${{env.PAGEFIND_VERSION}}
```

Alongside a version variable at the top of your workflow run:
```yml
env:
  PAGEFIND_VERSION: "0.10.6"
```

This action handles extracting the tar.gz and all that noise 🙂 (There might also be a way to construct that URL using `latest` if you don't want to manually version bump)
