### ISSUE TITLE
ReferenceError: url is not defined with Content-Security-Policy enabled

### ISSUE THREAD

**Issue by vanbroup** [CloudCannon/pagefind#21]
I'm trying to enable pagefind with `Content-Security-Policy` enabled and run into the following error:

```js
pagefind.js:1 
  Uncaught (in promise) ReferenceError: url is not defined
    at Pagefind.loadWasm (pagefind.js:1:12922)
    at async Promise.all (/blog/index 0)
    at async Pagefind.init (pagefind.js:1:12207)
loadWasm @ pagefind.js:1
await in loadWasm (async)
Pagefind @ pagefind.js:1
(anonymous) @ pagefind.js:1
```

Hugo config:
```yaml
server:
  headers:
  - for: /**
    values:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
      Permissions-Policy: document-domain=()
      Content-Security-Policy: default-src 'none'; img-src 'self' data:; form-action 'self'; base-uri 'self'; 
          block-all-mixed-content;
          style-src 'unsafe-inline' 'self' https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css https://fonts.googleapis.com/css;
          font-src https://fonts.gstatic.com/s/roboto/;
          script-src 'self' https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js;
          frame-src https://www.youtube-nocookie.com/ https://player.vimeo.com/;
          media-src https://i.ytimg.com https://www.rovid.nl/def/dco/2016/def-dco-20160823-idoa9bivg-web-hd.mp4;
          connect-src ws://localhost:1313/livereload 'self';
```
The `connect-src` option of the `Content-Security-Policy` is set to `self` which permits the script to connect (without this option you would get a policy error).

** copied the `/public/_pagefind` directory in my static Hugo folder for testing

This error is also live on: https://pkic.org/blog/

When running without `Content-Security-Policy` using the build in `--serve` option, the search runs fine:
```sh
hugo; ../pagefind --source ./public/  --serve 
```
