### ISSUE TITLE
Making result (pagefind-ui__result) clickable instead of title

### ISSUE THREAD

**Issue by alexanderameye** [CloudCannon/pagefind#606]
Right now, the element with class `pagefind-ui__result-link` is the one that is actually clickable. How is it possible to make the whole result clickable? (The `li` element with the class `pagefind-ui__result `)

**Comment by flyfoto** [comment]
Especially the optional image left to a result is expected by most userers to be a clickable link to the hit. see #235  posted long ago

**Comment by alexanderameye** [comment]
Is there any workaround possible?

**Comment by nhoizey** [comment]
I think it should be possible with these styles:

```css
.pagefind-ui__result {
  position: relative;
}

.pagefind-ui__result-link::after {
  position: absolute;
  inset: 0;
  display: block;
  content: "";
}
```
