### ISSUE TITLE
Allow to override default weight of HTML elements in config

### ISSUE THREAD

**Issue by SebouChu** [CloudCannon/pagefind#636]
I would like the possibility to set custom weight values for elements. Is it possible to add something like this in config instead of using the `data-pagefind-weight` attribute.

Maybe something like :

```
autoWeights:
  h1: 10
  h2: 9
  p: 1
  ...
```
