### ISSUE TITLE
Quick Question on hashes

### ISSUE THREAD

**Issue by DavidWells** [CloudCannon/pagefind#747]
What is determining the .pf_fragment and .pf_meta file postfix hashes?

<img width="387" alt="image" src="https://github.com/user-attachments/assets/a118392a-380b-405d-8e59-58f2d27b3bf9">

I was thinking about caching these files for a year+ for people to save on even more bandwidth. 

I'm guessing it's based on the generated output of the individual index/fragment files. Is this correct?

Thanks for the library by the way. It's Great!

**Comment by bglw** [comment]
👋  Correct! The postfix is a hash of the contents, so the intent is that all of these files can be cached indefinitely 🙂

**Comment by DavidWells** [comment]
Awesome thank you.

For anyone curious, I believe these are the correct cache headers in `netlify.toml` if you want to cache these index files

```toml
[[headers]]
  # Match all files in the "pagefind" directory with specific extensions
  for = "/pagefind/**/*.pf_*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
```
